# development url
@baseUrl = http://localhost:3333

#production url
# @baseUrl = https://rural-erm.onrender.com
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Geovane M.T",
  "email": "geovane4@test.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "geovane4@test.com.br",
  "password": "123456"
}

###

# @name refresh
PATCH {{baseUrl}}/token/refresh
Content-Type: application/json

{
  "email": "geovane@test.com.br",
  "password": "123456"
}

###

# @name create_producer
POST {{baseUrl}}/producers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Geovanne",
  "email": "geovane@email.com",
  "document": "48984114871"
}

###

# @name fetch_recent_producers
GET {{baseUrl}}/producers?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_producer_by_email
GET {{baseUrl}}/producers/geovane@email.com
Content-Type: application/json
Authorization: Bearer {{authToken}}