@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Geovane M.T",
  "email": "geovane@test.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "geovane@test.com.br",
  "password": "123456"
}

###

# @name create_producer
POST {{baseUrl}}/producers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Geovanne",
  "email": "ge@email.com",
  "document": "529.982.247-25",
}

###

# @name fetch_recent_producers
GET {{baseUrl}}/producers?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_producer_by_email
GET {{baseUrl}}/producers/ge@email.com
Content-Type: application/json
Authorization: Bearer {{authToken}}