# Development URL
# @baseUrl = http://localhost:3333

# Production URL
@baseUrl = https://your-production-url.com
@authToken = {{authenticate.response.body.access_token}}

###

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "your name",
  "email": "your email",
  "password": "your password"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "your email",
  "password": "your password"
}

###

# @name create_producer
POST {{baseUrl}}/producers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "producer_name",
  "email": "producer_email@example.com",
  "document": "producer_document"
}

###

# @name fetch_recent_producers
GET {{baseUrl}}/producers?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_producer_by_email
GET {{baseUrl}}/producers/producer_email@example.com
Content-Type: application/json
Authorization: Bearer {{authToken}}
